# Generated by Django 5.0.13 on 2025-04-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task",
                to="application.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sheet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_set",
                to="application.tasksheet",
                verbose_name="Лист задач",
            ),
        ),
    ]
